language: python

before_install:
  # for rpm-py-installer
  - sudo apt-get install -y rpm

install:
 - pip install --upgrade pip setuptools
 - pip install tox

script:
  - tox

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27-django18
  - python: "2.7"
    env: TOXENV=py27-django111
  - python: "3.4"
    env: TOXENV=py34-django18
  - python: "3.5"
    env: TOXENV=py35-django111
  - python: "3.6"
    env: TOXENV=py36-django18 DEPLOY=1
  - python: "3.7"
    env: TOXENV=py37-django111
  - python: "3.7"
    env: TOXENV=py37-cov-travis

deploy:
  # Tagging a new kobo automatically releases to PyPI.
  provider: pypi
  user: __token__
  password:
    secure: l4WpTkevP5O2SHEtVgtj83KnW0QrcS0WsDDXYNU3e+lZpfUc9e6DLahuLq/B2NEF618JrHSzcq2nYsLJgOOvSiT+hBxgYunKncQTLg8I9fnlPbcowhCtacjVb4pNN0eyW275ymjvizKoqhY0rPZVQj9gYxsiOF9n+tagGGDcmGEx6pwStkYVnqfFccmBggilkTx3myvCmJMsvt11ukw4oH3inIpzR+BvnIGkOurCUWKigOukxp+ssB0e+yqjmKtDVmGUGfIyMFb2RGq1aCeruvzYLvpj/GkfxqynOrmJ5XpeC6mtRS9VzdqKwfDF9tf3gLj0z0jZYA6jj2zqf7x+0Vckxi4dnVYEcENobMbAFlATaKS1IaWwnax7ZblvgCYYnj5+IEXtF9Etjh/0A7eU8G4Im8IfCelkkzKlvEpJgFaObBh39muj5dmyxojYCHYr5s/eGLCjuqwwn8QhH/JrFlkNDj3NV/G0Bk2/iO843pnb9t76UNKm+6G76UwsG71d8uD1GlrVlRA0jcb8+lJicLbD7/PSForbIUq/8HKvn5GVx5fBlJG+UNrLle5NgKSJ2hgDDGUWHibrWwOTuC3bEtglMFYy2x6GXV622cWuQBCBIncKZUtULyFjPz3jQJJQ0hLPWAv3R183i483uQ7BMsLfZP3AySFFFdeuroyqac4=
  on:
    tags: true
    # Only one of the environments in the matrix should have
    # deployments enabled. It's mostly arbitrary which one,
    # but best to select some Python 3.x so up-to-date tools
    # are used during release.
    condition: $DEPLOY = 1
  skip_existing: true
